import React from 'react';
import {
  SiPostgresql,
  SiTypescript,
  SiMongodb,
  SiMysql,
  SiRedux,
  SiRecoil,
  SiHono,
  SiJira,
  SiExpress,
  SiReactquery,
  SiDaisyui,
  SiPrisma,
  SiNpm,
  SiMongoose,
  SiTurborepo,
  SiNetlify,
  SiRender,
  SiCloudflare,
} from 'react-icons/si';
import {
  FaHtml5,
  FaCss3Alt,
  FaReact,
  FaNodeJs,
  FaDocker,
  FaJava,
  FaAws,
  FaGithub,
  FaBitbucket,
} from 'react-icons/fa';
import { TbBrandSocketIo } from 'react-icons/tb';
import { IoLogoJavascript } from 'react-icons/io5';
import { RiNextjsFill, RiTailwindCssFill } from 'react-icons/ri';

export const SkillsUtils = [
  { name: 'HTML', icon: <FaHtml5 size={50} /> },
  { name: 'CSS', icon: <FaCss3Alt size={50} /> },
  { name: 'JS', icon: <IoLogoJavascript size={50} /> },
  { name: 'Typescript', icon: <SiTypescript size={50} /> },
  { name: 'React', icon: <FaReact size={50} /> },
  { name: 'MongoDB', icon: <SiMongodb size={50} /> },
  { name: 'Mongoose', icon: <SiMongoose size={50} /> },
  { name: 'Postgresql', icon: <SiPostgresql size={50} /> },
  { name: 'Node.js', icon: <FaNodeJs size={50} /> },
  { name: 'Docker', icon: <FaDocker size={50} /> },
  { name: 'Java', icon: <FaJava size={50} /> },
  { name: 'MySql', icon: <SiMysql size={50} /> },
  { name: 'Next.js', icon: <RiNextjsFill size={50} /> },
  { name: 'Tailwind', icon: <RiTailwindCssFill size={50} /> },
  { name: 'Redux', icon: <SiRedux size={50} /> },
  { name: 'Recoil', icon: <SiRecoil size={50} /> },
  { name: 'Hono', icon: <SiHono size={50} /> },
  { name: 'AWS', icon: <FaAws size={50} /> },
  { name: 'Jira', icon: <SiJira size={50} /> },
  { name: 'Github', icon: <FaGithub size={50} /> },
  { name: 'Bitbucket', icon: <FaBitbucket size={50} /> },
  { name: 'Socket.IO', icon: <TbBrandSocketIo size={50} /> },
  { name: 'Express.js', icon: <SiExpress size={50} /> },
  { name: 'react_query', icon: <SiReactquery size={50} /> },
  { name: 'daisyUI', icon: <SiDaisyui size={50} /> },
  { name: 'Prisma', icon: <SiPrisma size={50} /> },
  { name: 'npm', icon: <SiNpm size={50} /> },
  { name: 'Turborepo', icon: <SiTurborepo size={50} /> },
  { name: 'Netlify', icon: <SiNetlify size={50} /> },
  { name: 'Render', icon: <SiRender der size={50} /> },
  { name: 'Cloudflare', icon: <SiCloudflare size={50} /> },
];
